import express from 'express';
import prisma from '../../db/connection.js';
import { authenticate } from '../../core/auth.js';
import { generateDownloadUrl } from '../../services/s3Service.js';
import { validateTenant } from '../../middleware/tenantValidation.js';
import { logAudit } from '../../services/auditService.js';
import { RECORDING_STOP, DOWNLOAD } from '../../constants/auditActions.js';

const router = express.Router();

// All recording routes require authentication
router.use(authenticate);
router.use(validateTenant);

/**
 * POST /api/v1/recordings
 * Handle recording stop flow: link to order and save metadata
 *
 * Request body:
 * {
 *   "package_code": "PKG-99123",
 *   "duration": 42,
 *   "file_size": 20971520,
 *   "bucket": "packvision-bucket",
 *   "object_key": "tenant_a/orders/ord_123/rec_456.webm",
 *   "started_at": "2026-01-08T18:00:00Z",
 *   "ended_at": "2026-01-08T18:00:42Z"
 * }
 */
router.post('/recordings', async (req, res) => {
  try {
    const {
      package_code,
      duration,
      file_size,
      bucket,
      object_key,
      started_at,
      ended_at,
    } = req.body;
    const { tenant_id, id: user_id } = req.user;

    if (!package_code) {
      return res.status(400).json({ error: 'package_code is required' });
    }

    // 1. Find or create order using tenant_id + package_code
    let order_id;
    const orderResult = await prisma.order.findFirst({
      where: { tenantId: tenant_id, packageCode: package_code },
      select: { id: true }
    });

    if (!orderResult) {
      // Auto-create order if it doesn't exist to prevent failure
      console.log(
        `Order not found for package_code ${package_code}. Creating placeholder order with 'packed' status.`,
      );
      const newOrderResult = await prisma.order.create({
        data: {
          tenantId: tenant_id,
          packageCode: package_code,
          status: 'packed',
          externalOrderId: `EXT-${Date.now()}`
        },
        select: { id: true }
      });
      order_id = newOrderResult.id;
    } else {
      order_id = orderResult.id;
    }

    // 2. Insert into recordings
    // Note: The object_key convention mentioned in user request: {tenant_id}/{order_id}/{recording_id}.webm
    // Usually, the recording_id is generated by the database.
    // If the frontend already knows the object_key, we use it.

    const insertResult = await prisma.recording.create({
      data: {
        tenantId: tenant_id,
        orderId: order_id,
        userId: user_id,
        bucket: bucket || process.env.AWS_S3_BUCKET_NAME || 'test-bucket',
        objectKey: object_key,
        fileSize: file_size,
        durationSeconds: duration,
        startedAt: started_at ? new Date(started_at) : new Date(),
        endedAt: ended_at ? new Date(ended_at) : new Date(),
        status: 'completed',
      },
      select: { id: true }
    });

    // Audit Log: RECORDING_STOP
    logAudit({
      tenant_id,
      actor_id: user_id,
      action: RECORDING_STOP,
      entity_type: 'recording',
      entity_id: insertResult.id,
      metadata: {
        order_id,
        bucket,
        object_key,
        duration,
        file_size,
      },
    });

    res.status(201).json({
      message: 'Recording linked successfully',
      recording_id: insertResult.id,
    });
  } catch (error) {
    console.error('Error saving recording:', error);
    res.status(500).json({ error: 'Failed to save recording information' });
  }
});

/**
 * GET /api/v1/recordings/:id/presigned-url
 * Get a presigned URL for playback
 */
router.get('/recordings/:id/presigned-url', async (req, res) => {
  try {
    const { id } = req.params;
    const { tenant_id } = req.user;

    // 1. Get bucket and object_key from DB, ensuring tenant-scoped
    const recording = await prisma.recording.findFirst({
      where: { id, tenantId: tenant_id },
      select: { bucket: true, objectKey: true }
    });

    if (!recording) {
      return res
        .status(404)
        .json({ error: 'Recording not found or access denied' });
    }

    const { bucket, objectKey: object_key } = recording;

    // 2. Generate presigned URL (valid for 120 seconds as per request)
    const presignedUrl = await generateDownloadUrl(object_key, 120, bucket);

    // Audit Log: DOWNLOAD
    logAudit({
      tenant_id: req.user.tenant_id,
      actor_id: req.user.id,
      action: DOWNLOAD,
      entity_type: 'recording',
      entity_id: id,
      metadata: { bucket, object_key, reason: 'playback' },
    });

    res.json({
      presignedUrl,
      expires_in: 120,
    });
  } catch (error) {
    console.error('Error generating presigned URL:', error);
    res.status(500).json({ error: 'Failed to generate playback URL' });
  }
});

export default router;
