import express from 'express';
import { query } from '../../db/connection.js';
import { authenticate } from '../../core/auth.js';
import { generateDownloadUrl } from '../../services/s3Service.js';
import { validateTenant } from '../../middleware/tenantValidation.js';

const router = express.Router();

// All recording routes require authentication
router.use(authenticate);
router.use(validateTenant);

/**
 * POST /api/v1/recordings
 * Handle recording stop flow: link to order and save metadata
 *
 * Request body:
 * {
 *   "package_code": "PKG-99123",
 *   "duration": 42,
 *   "file_size": 20971520,
 *   "bucket": "packvision-bucket",
 *   "object_key": "tenant_a/orders/ord_123/rec_456.webm",
 *   "started_at": "2026-01-08T18:00:00Z",
 *   "ended_at": "2026-01-08T18:00:42Z"
 * }
 */
router.post('/recordings', async (req, res) => {
  try {
    const {
      package_code,
      duration,
      file_size,
      bucket,
      object_key,
      started_at,
      ended_at,
    } = req.body;
    const { tenant_id, id: user_id } = req.user;

    if (!package_code) {
      return res.status(400).json({ error: 'package_code is required' });
    }

    // 1. Find or create order using tenant_id + package_code
    let order_id;
    const orderResult = await query(
      'SELECT id FROM orders WHERE tenant_id = $1 AND package_code = $2',
      [tenant_id, package_code],
    );

    if (orderResult.rows.length === 0) {
      // Auto-create order if it doesn't exist to prevent failure
      console.log(
        `Order not found for package_code ${package_code}. Creating placeholder order with 'packed' status.`,
      );
      const newOrderResult = await query(
        `INSERT INTO orders (tenant_id, package_code, status, external_order_id)
         VALUES ($1, $2, $3, $4) RETURNING id`,
        [tenant_id, package_code, 'packed', `EXT-${Date.now()}`],
      );
      order_id = newOrderResult.rows[0].id;
    } else {
      order_id = orderResult.rows[0].id;
    }

    // 2. Insert into recordings
    // Note: The object_key convention mentioned in user request: {tenant_id}/{order_id}/{recording_id}.webm
    // Usually, the recording_id is generated by the database.
    // If the frontend already knows the object_key, we use it.

    const insertResult = await query(
      `INSERT INTO recordings (
        tenant_id, order_id, user_id, bucket, object_key, 
        file_size, duration_seconds, started_at, ended_at, status
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
      RETURNING id`,
      [
        tenant_id,
        order_id,
        user_id,
        bucket || process.env.AWS_S3_BUCKET_NAME || 'test-bucket',
        object_key,
        file_size,
        duration,
        started_at || new Date().toISOString(),
        ended_at || new Date().toISOString(),
        'completed',
      ],
    );

    res.status(201).json({
      message: 'Recording linked successfully',
      recording_id: insertResult.rows[0].id,
    });
  } catch (error) {
    console.error('Error saving recording:', error);
    res.status(500).json({ error: 'Failed to save recording information' });
  }
});

/**
 * GET /api/v1/recordings/:id/presigned-url
 * Get a presigned URL for playback
 */
router.get('/recordings/:id/presigned-url', async (req, res) => {
  try {
    const { id } = req.params;
    const { tenant_id } = req.user;

    // 1. Get bucket and object_key from DB, ensuring tenant-scoped
    const result = await query(
      'SELECT bucket, object_key FROM recordings WHERE id = $1 AND tenant_id = $2',
      [id, tenant_id],
    );

    if (result.rows.length === 0) {
      return res
        .status(404)
        .json({ error: 'Recording not found or access denied' });
    }

    const { bucket, object_key } = result.rows[0];

    // 2. Generate presigned URL (valid for 120 seconds as per request)
    const presignedUrl = await generateDownloadUrl(object_key, 120, bucket);

    res.json({
      presignedUrl,
      expires_in: 120,
    });
  } catch (error) {
    console.error('Error generating presigned URL:', error);
    res.status(500).json({ error: 'Failed to generate playback URL' });
  }
});

export default router;
